home/urls.py
from django.urls import path, include
from . import views


app_name='home'

Backet_urls= [
    path('', views.BucketHome.as_view(), name='bucket'),
    path('delete_obj/<key>', views.DeleteBucketObj.as_view(), name='delete_obj_bucket'),
    path('download_obj/<key>', views.DownloadBucketObj.as_view(), name='download_obj_bucket'),  
    path('upload_obj/', views.UploadBucketObj.as_view(), name='upload_obj_bucket'),      
]


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('bucket/', include(Backet_urls)),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static( MEDIA_URL, document_root= MEDIA_ROOT)

home/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name= models.CharField(max_length= 200)
    slug= models.SlugField(max_length= 200, unique= True)

    class Meta:
        ordering= ('name',)
        verbose_name= 'Category'
        verbose_name_plural= 'Categories'

    def __str__(self):
        return self.name   


class Product(models.Model):
    category= models.ForeignKey("Category", on_delete=models.CASCADE, related_name= "Products")
    name= models.CharField(max_length= 200)
    slug= models.SlugField(max_length= 200, unique= True)
    image= models.ImageField()
    description= models.TextField()
    price= models.DecimalField(max_digits=5, decimal_places=2)
    available= models.BooleanField(default= True)
    created_at= models.DateTimeField(auto_now_add= True)
    updated_at= models.DateTimeField(auto_now= True)

    class Meta:
        ordering= ('name',)

    def __str__(self):
        return self.name  

    def get_absolute_url(self):
        return reverse('home:product_detail', args= [self.slug,])

home/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Product
from . import tasks
from django.contrib import messages
from django.shortcuts import render, redirect
from utils import IsAdminUserMixin


class HomeView(View):
    def get(self, request):
        products= Product.objects.filter(available= True)
        return render(request, 'home/home.html', {'products': products})


class ProductDetailView(View):
    def get(self, request, slug):
        product= get_object_or_404(Product, slug= slug)
        return render(request, 'home/product_detail.html', {'product': product})


class BucketHome(IsAdminUserMixin, View):
    bucket_template= 'home/bucket.html'
 
    def get(self, request):
        objects= tasks.all_bucket_objects_task()
        return render(request, self.bucket_template, {'objects': objects})


class DeleteBucketObj(IsAdminUserMixin, View): 
    def get(self, request, key):
        tasks.delete_bucket_object_task(key)
        messages.success(request, "your object will be delete soon", 'info')
        return redirect('home:bucket')


class DownloadBucketObj(IsAdminUserMixin, View):
    def get(self, request, key):
        tasks.download_bucket_object_task(key)
        messages.success(request, "your object will be download soon", 'info')
        return redirect('home:bucket')
    

class UploadBucketObj(IsAdminUserMixin, View):
    def get(self, request):
        tasks.upload_bucket_object_task()
        messages.success(request, "your object will be upload soon", 'info')
        return redirect('home:bucket')
        

home/templates/home/bucket.html
{% extends "base.html" %}

{% block content %}
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="row"><a href= {% url "home:upload_obj_bucket" %}>upload</a></th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>   
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Name</th>
        <th scope="col">Size</th>
        <th scope="col">Delete</th>
        <th scope="col">Download</th>
      </tr>
    </thead>
    <tbody>
    {% for obj in objects %}  
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ obj.Key }}</td>
        <td>{{ obj.Size| filesizeformat }}</td>
        <td><a href= {% url "home:delete_obj_bucket" obj.Key %}>delete</a></td>        
        <td><a href= {% url "home:download_obj_bucket" obj.Key %}>download</a></td>
      </tr>
    {% endfor %}   
    </tbody>
  </table>
{% endblock %}

home/templates/home/home.html
{% extends "base.html" %}
{% load static %}

{% block extra_headers %}
<link rel="stylesheet" href= "{% static 'home/css/style.css' %}">
{% endblock extra_headers %}

{% block content %}
<div class="card-container">
    {% for product in products %} 
            <div class="card" style="width: 18rem;">
                <img src="{{ product.image.url }}" class="card-img-top">
                <div class="card-body">
                    <a href= "{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
                </div>
            </div>
        </br>
    {% endfor %}
{% endblock %}

home/templates/home/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_headers %}
<link rel="stylesheet" href= "{% static 'home/css/style.css' %}">
{% endblock extra_headers %}

{% block content %}   
    <img src="{{ product.image.url }}"></br>
    <h3>{{ product.name }}</h3>
    <h5>{{ product.price }} $</h5>
    <h5>{{ product.description }}</h5>
    <small>{{ product.created_at }}</small>                          
{% endblock %}