accounts/urls.py
from django.urls import path
from . import views


app_name= 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name= 'user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name= 'verify_code'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
]

home/urls.py
from django.urls import path, include
from . import views


app_name='home'

Backet_urls= [
    path('', views.BucketHome.as_view(), name='bucket'),
    path('delete_obj/<key>', views.DeleteBucketObj.as_view(), name='delete_obj_bucket'),
    path('download_obj/<key>', views.DownloadBucketObj.as_view(), name='download_obj_bucket'),  
    path('upload_obj/', views.UploadBucketObj.as_view(), name='upload_obj_bucket'),      
]


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('bucket/', include(Backet_urls)),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static( MEDIA_URL, document_root= MEDIA_ROOT)

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}  
{% endif %}      

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <div class="navbar-nav">
        <h5><a class="nav-link active" href="{% url "home:home" %}">Home</a></h5>
        {% if request.user.is_authenticated %}
          <h5><a class="nav-link active" href="{% url "accounts:logout" %}">Logout</a></h5>
        {% else %} 
          <h5><a class="nav-link active" href="{% url "accounts:user_register" %}">Register</a></h5>
          <h5><a class="nav-link active" href="{% url "accounts:login" %}">Login</a></h5>
        {% endif %}
        {% if request.user.is_admin %}
          <h5><a class="nav-link active" href="{% url "home:bucket" %}">Bucket</a></h5>
        {% endif %}  
      </div>
    </div>
</nav>